[global]
run_eval = true

[ops.reduce]
impl = [
    { backend = "cuda", versions = ["v0"] },
    { backend = "triton", versions = ["v0"] }
]
num_warmup = 10
num_eval = 20
tolerance = 1e-3

[ops.gemm]
impl = [
    { backend = "cuda", versions = ["v0"] },
    { backend = "triton", versions = ["v0"] },
    { backend = "tilelang", versions = ["v0"] },
]
num_warmup = 10
num_eval = 30
tolerance = 1e-2

[ops.attention]
impl = [
    { backend = "cuda", versions = ["v0"] },
    { backend = "triton", versions = ["v0"] }
]
num_warmup = 10
num_eval = 30
tolerance = 1e-3

[ops.vadd]
impl = [
    { backend = "cuda", versions = ["v0"] },
    { backend = "triton", versions = ["v0"] },
    { backend = "tilelang", versions = ["v0"] },
]
num_warmup = 100
num_eval = 10
tolerance = 1e-3
